teste return code

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -26,9 +26,15 @@ jobs:
                  WORKFLOW_FILE=$(_jq '.workflow_file')
                  TAG=$(_jq '.tag')
 
-                 curl -X POST -H "Accept: application/vnd.github.v3+json" \
+                 curl -s -X POST -H "Accept: application/vnd.github.v3+json" \
                  -H "Authorization: token ${{ secrets.PAT }}" \
                  https://api.github.com/repos/malaquiasLAB/$REPOSITORY/actions/workflows/$WORKFLOW_FILE/dispatches \
                  -d '{"ref":"'$TAG'"}'
+
+                 if [ $? -eq 0 ]; then
+                   echo "Workflow $WORKFLOW_FILE triggered successfully for $REPOSITORY"
+                 else
+                   echo "Failed to trigger workflow $WORKFLOW_FILE for $REPOSITORY"
+                 fi
             done
       shell: bash
